### ISSUE TITLE
For some help

### ISSUE THREAD

**Issue by biulding-Dh** [starain-xinxin/LDPC-star#1]
你好，如你所说，这个项目是复旦大学的课设，我想问一下是否有这门课设的PPT，我想进一步学习一下LDPC编解码的原理，谢谢。

**Comment by starain-xinxin** [comment]
[信道编码7 LDPC码.pdf](https://github.com/user-attachments/files/17990826/7.LDPC.pdf)
这是LDPC章节的PPT
另：这份代码只是匆忙编写的结果，我并不能保证这些code的正确性，只是结果看起来还不错...
请谨慎参考
![译码](https://github.com/user-attachments/assets/45190d76-6dba-4a1d-954c-b98ea4d43997)
